INSERT INTO public.push_notification_configs (
  key,
  is_enabled,
  auto_send_enabled,
  message_title,
  message_body,
  schedule_type,
  send_day_of_week,
  send_day_of_month,
  send_hour,
  send_minute,
  timezone,
  trigger_condition,
  delivery_window_start_hour,
  delivery_window_end_hour
) VALUES (
  'week_budget_setup',
  true,
  false,
  'Sæt ugens rådighedsbeløb',
  'Din nye uge er i gang. Sæt rådighedsbeløbet, så Kuvert passer med virkeligheden.',
  'weekly',
  1,
  null,
  11,
  0,
  'Europe/Copenhagen',
  'both',
  9,
  20
)
ON CONFLICT (key) DO UPDATE SET
  message_title = EXCLUDED.message_title,
  message_body = EXCLUDED.message_body,
  schedule_type = EXCLUDED.schedule_type,
  send_day_of_week = EXCLUDED.send_day_of_week,
  send_day_of_month = EXCLUDED.send_day_of_month,
  send_hour = EXCLUDED.send_hour,
  send_minute = EXCLUDED.send_minute,
  timezone = EXCLUDED.timezone,
  trigger_condition = EXCLUDED.trigger_condition,
  delivery_window_start_hour = EXCLUDED.delivery_window_start_hour,
  delivery_window_end_hour = EXCLUDED.delivery_window_end_hour,
  updated_at = now();
